export class SpeakerRegisterModalElements {

    public static readonly ELEMENTS: Map<string, HTMLElement> = new Map([

        ['speaker_register_label_title',                    document.querySelector('#speaker_register_label_title')],
        ['speaker_register_data_id',                        document.querySelector('#speaker_register_data_id')],
        ['speaker_register_label_name',                     document.querySelector('#speaker_register_label_name')],
        ['speaker_register_data_name',                      document.querySelector('#speaker_register_data_name')],
        ['speaker_register_label_jobInstitute',             document.querySelector('#speaker_register_label_jobInstitute')],
        ['speaker_register_data_jobInstitute',              document.querySelector('#speaker_register_data_jobInstitute')],
        ['speaker_register_label_description',              document.querySelector('#speaker_register_label_description')],
        ['speaker_register_data_description',               document.querySelector('#speaker_register_data_description')],
        ['speaker_register_label_socialNetworks',           document.querySelector('#speaker_register_label_socialNetworks')],
        ['speaker_register_label_socialNetworks-facebook',  document.querySelector('#speaker_register_label_socialNetworks-facebook')],
        ['speaker_register_label_socialNetworks-twitter',   document.querySelector('#speaker_register_label_socialNetworks-twitter')],
        ['speaker_register_label_socialNetworks-lattes',    document.querySelector('#speaker_register_label_socialNetworks-lattes')],
        ['speaker_register_label_socialNetworks-github',    document.querySelector('#speaker_register_label_socialNetworks-github')],
        ['speaker_register_label_socialNetworks-youtube',   document.querySelector('#speaker_register_label_socialNetworks-youtube')],
        ['speaker_register_label_socialNetworks-spotify',   document.querySelector('#speaker_register_label_socialNetworks-spotify')],
        ['speaker_register_label_socialNetworks-behance',   document.querySelector('#speaker_register_label_socialNetworks-behance')],
        ['speaker_register_label_socialNetworks-skype',     document.querySelector('#speaker_register_label_socialNetworks-skype')],
        ['speaker_register_label_socialNetworks-linkedin',  document.querySelector('#speaker_register_label_socialNetworks-linkedin')],
        ['speaker_register_label_socialNetworks-pinterest', document.querySelector('#speaker_register_label_socialNetworks-pinterest')],
        ['speaker_register_label_socialNetworks-blog',      document.querySelector('#speaker_register_label_socialNetworks-blog')],
        ['speaker_register_data_socialNetworks',            document.querySelector('#speaker_register_data_socialNetworks')],
        ['speaker_register_data_socialNetworks-facebook',   document.querySelector('#speaker_register_data_socialNetworks-facebook')],
        ['speaker_register_data_socialNetworks-twitter',    document.querySelector('#speaker_register_data_socialNetworks-twitter')],
        ['speaker_register_data_socialNetworks-lattes',     document.querySelector('#speaker_register_data_socialNetworks-lattes')],
        ['speaker_register_data_socialNetworks-github',     document.querySelector('#speaker_register_data_socialNetworks-github')],
        ['speaker_register_data_socialNetworks-youtube',    document.querySelector('#speaker_register_data_socialNetworks-youtube')],
        ['speaker_register_data_socialNetworks-spotify',    document.querySelector('#speaker_register_data_socialNetworks-spotify')],
        ['speaker_register_data_socialNetworks-behance',    document.querySelector('#speaker_register_data_socialNetworks-behance')],
        ['speaker_register_data_socialNetworks-skype',      document.querySelector('#speaker_register_data_socialNetworks-skype')],
        ['speaker_register_data_socialNetworks-linkedin',   document.querySelector('#speaker_register_data_socialNetworks-linkedin')],
        ['speaker_register_data_socialNetworks-pinterest',  document.querySelector('#speaker_register_data_socialNetworks-pinterest')],
        ['speaker_register_data_socialNetworks-blog',       document.querySelector('#speaker_register_data_socialNetworks-blog')],
        ['speaker_register_label_email',                    document.querySelector('#speaker_register_label_email')],
        ['speaker_register_data_email',                     document.querySelector('#speaker_register_data_email')],
        ['speaker_register_label_avatar',                   document.querySelector('#speaker_register_label_avatar')],
        ['speaker_register_data_avatar',                    document.querySelector('#speaker_register_data_avatar')],
        ['speaker_register_label_avatar2',                  document.querySelector('#speaker_register_label_avatar2')],
        ['speaker_register_button_create',                  document.querySelector('#speaker_register_button_create')],
        ['speaker_register_button_update',                  document.querySelector('#speaker_register_button_update')],
        ['speaker_register_label_helper-name',              document.querySelector('#speaker_register_label_helper-name')],
        ['speaker_register_label_helper-jobInstitute',      document.querySelector('#speaker_register_label_helper-jobInstitute')],
        ['speaker_register_label_helper-description',       document.querySelector('#speaker_register_label_helper-description')],
        ['dataForm',                                        document.querySelector('#dataForm')],

    ]);

}